# Eigenvalues and Eigenvectors

In [1]:
# Reload the notebook if an external file is updated
%load_ext autoreload
%autoreload 2

import sys
    
from pathlib import Path

path = (
    Path
    .cwd()
    .parent
    .parent
    .joinpath('project')
)

sys.path.append(path)

In [2]:
from __future__ import annotations

import numpy as np
import pandas as pd
import sympy as sp

from project.reduction import (
    DimensionalityReduction,
    PCAStrategy
)
from project.visualizer.pca import (
    MatplotlibVisualizer,
    PCAVisualizer,
    PlotlyVisualizer
)
from project.visualizer.settings import Settings
from sklearn.datasets import (
    load_digits,
    load_iris,
    load_wine
)
from sklearn.preprocessing import StandardScaler

In [3]:
scale = True

loader = load_iris()

columns, data, target = (
    loader.feature_names,
    loader.data,
    loader.target
)

dataframe = pd.DataFrame(columns=columns, data=data)

In [4]:
scaler = StandardScaler()
scale = scaler.fit_transform(dataframe)

In [5]:
dataframe.loc[:, dataframe.columns] = scale

dataframe

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0            -0.900681          1.019004          -1.340227         -1.315444
1            -1.143017         -0.131979          -1.340227         -1.315444
2            -1.385353          0.328414          -1.397064         -1.315444
3            -1.506521          0.098217          -1.283389         -1.315444
4            -1.021849          1.249201          -1.340227         -1.315444
..                 ...               ...                ...               ...
145           1.038005         -0.131979           0.819596          1.448832
146           0.553333         -1.282963           0.705921          0.922303
147           0.795669         -0.131979           0.819596          1.053935
148           0.432165          0.788808           0.933271          1.448832
149           0.068662         -0.131979           0.762758          0.790671

[150 rows x 4 columns]

In [6]:
covariance = np.cov(dataframe.T)
covariance

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

In [7]:
matrix = sp.Matrix(covariance)
eigenvector  = matrix.eigenvects()

eigenvector

[(2.93808505020000,
  1,
  [Matrix([
   [ -0.52106591467012],
   [ 0.269347442505943],
   [-0.580413095796294],
   [-0.564856535779361]])]),
 (0.920164904162488,
  1,
  [Matrix([
   [ -0.377417615564567],
   [ -0.923295659540715],
   [-0.0244916090855863],
   [-0.0669419869680587]])]),
 (0.0208538621764622,
  1,
  [Matrix([
   [ 0.261286279952452],
   [-0.123509619585519],
   [-0.801449246335988],
   [ 0.523597134566191]])]),
 (0.147741821044948,
  1,
  [Matrix([
   [ 0.719566352700817],
   [-0.244381779514399],
   [-0.142126369333904],
   [-0.634272737110923]])])]

In [8]:
eigenvalues, eigenvectors = np.linalg.eig(covariance)

In [9]:
eigenvalues

array([2.93808505, 0.9201649 , 0.14774182, 0.02085386])

In [11]:
rounded = np.round(eigenvalues, decimals=2)
rounded

array([2.94, 0.92, 0.15, 0.02])

In [10]:
eigenvectors

array([[ 0.52106591, -0.37741762, -0.71956635,  0.26128628],
       [-0.26934744, -0.92329566,  0.24438178, -0.12350962],
       [ 0.5804131 , -0.02449161,  0.14212637, -0.80144925],
       [ 0.56485654, -0.06694199,  0.63427274,  0.52359713]])

In [12]:
rounded = np.round(eigenvectors, decimals=2)
rounded

array([[ 0.52, -0.38, -0.72,  0.26],
       [-0.27, -0.92,  0.24, -0.12],
       [ 0.58, -0.02,  0.14, -0.8 ],
       [ 0.56, -0.07,  0.63,  0.52]])